/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2050RouteImport } from './routes/2050'
import { Route as HorizonRouteImport } from './routes/horizon'
import { Route as NowRouteImport } from './routes/now'
import { Route as PowerRouteImport } from './routes/power'
import { Route as PromiseRouteImport } from './routes/promise'
import { Route as RiskRouteImport } from './routes/risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2050Route = R2050RouteImport.update({
  id: '/2050',
  path: '/2050',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizonRoute = HorizonRouteImport.update({
  id: '/horizon',
  path: '/horizon',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2050': typeof R2050Route
  '/horizon': typeof HorizonRoute
  '/now': typeof NowRoute
  '/power': typeof PowerRoute
  '/promise': typeof PromiseRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2050': typeof R2050Route
  '/horizon': typeof HorizonRoute
  '/now': typeof NowRoute
  '/power': typeof PowerRoute
  '/promise': typeof PromiseRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2050': typeof R2050Route
  '/horizon': typeof HorizonRoute
  '/now': typeof NowRoute
  '/power': typeof PowerRoute
  '/promise': typeof PromiseRoute
  '/risk': typeof RiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/2050' | '/horizon' | '/now' | '/power' | '/promise' | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/2050' | '/horizon' | '/now' | '/power' | '/promise' | '/risk'
  id:
    | '__root__'
    | '/'
    | '/2050'
    | '/horizon'
    | '/now'
    | '/power'
    | '/promise'
    | '/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2050Route: typeof R2050Route
  HorizonRoute: typeof HorizonRoute
  NowRoute: typeof NowRoute
  PowerRoute: typeof PowerRoute
  PromiseRoute: typeof PromiseRoute
  RiskRoute: typeof RiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2050': {
      id: '/2050'
      path: '/2050'
      fullPath: '/2050'
      preLoaderRoute: typeof R2050RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizon': {
      id: '/horizon'
      path: '/horizon'
      fullPath: '/horizon'
      preLoaderRoute: typeof HorizonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2050Route: R2050Route,
  HorizonRoute: HorizonRoute,
  NowRoute: NowRoute,
  PowerRoute: PowerRoute,
  PromiseRoute: PromiseRoute,
  RiskRoute: RiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
